import type { CSSProperties } from 'react'

export const editableRootStyle = {
  // AWSA-inspired premium system: a calm light canvas, near-black ink, a single
  // vivid emerald-green signature accent, and deep near-black "inverted" panels
  // (nav, hero, footer, CTA) for high-contrast agency rhythm. Flat surfaces,
  // hairline borders, refined shadows. Every editable surface reads these vars,
  // so changing the palette here updates the whole site consistently.
  '--slot4-page-bg': '#f6f8f4',
  '--slot4-page-text': '#0e1311',
  '--slot4-panel-bg': '#eef1ea',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#5b625a',
  '--slot4-soft-muted-text': '#8b938a',
  '--slot4-accent': '#0bab5b',
  '--slot4-accent-fill': '#0bab5b',
  '--slot4-accent-soft': '#e4f7ec',
  '--slot4-accent-bright': '#34e283',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#0a0f0c',
  '--slot4-dark-soft': '#0f1712',
  '--slot4-dark-panel': '#121a15',
  '--slot4-dark-text': '#f3f6f1',
  '--slot4-dark-muted': '#9aa79d',
  '--slot4-dark-border': 'rgba(255,255,255,0.10)',
  '--slot4-media-bg': '#e7eae3',
  '--slot4-cream': '#ffffff',
  '--slot4-warm': '#eef1ea',
  '--slot4-lavender': '#ffffff',
  '--slot4-gray': '#eef1ea',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#f6f8f4',
  '--editable-page-text': '#0e1311',
  '--editable-container': '1320px',
  '--editable-radius': '1.25rem',
  '--editable-border': '#e3e7df',
  '--editable-nav-bg': '#0a0f0c',
  '--editable-nav-text': '#f3f6f1',
  '--editable-nav-active': '#34e283',
  '--editable-nav-active-text': '#0a0f0c',
  '--editable-cta-bg': '#0bab5b',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#0a0f0c',
  '--editable-footer-text': '#f3f6f1',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-[var(--slot4-dark-border)]',
  shadow: 'shadow-[0_1px_2px_rgba(13,19,16,0.04),0_8px_24px_-12px_rgba(13,19,16,0.12)]',
  shadowStrong: 'shadow-[0_24px_60px_-20px_rgba(13,19,16,0.30)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(10,15,12,0.05),rgba(10,15,12,0.78))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-6 lg:px-8',
    sectionY: 'py-16 sm:py-20 lg:py-28',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[150px] shrink-0 snap-start sm:w-[170px]',
  },
  type: {
    eyebrow: 'inline-flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.26em] text-[var(--slot4-accent)]',
    heroTitle: 'text-balance text-4xl font-semibold leading-[1.04] tracking-[-0.03em] sm:text-5xl lg:text-[3.5rem]',
    sectionTitle: 'text-3xl font-semibold tracking-[-0.025em] sm:text-4xl lg:text-[2.75rem]',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-[var(--editable-radius)] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[var(--editable-radius)] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[var(--editable-radius)] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-7 py-3.5 text-sm font-semibold tracking-[0.01em] text-[var(--slot4-on-accent)] transition duration-300 hover:brightness-[1.08] hover:shadow-[0_12px_30px_-10px_var(--slot4-accent-fill)] active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-7 py-3.5 text-sm font-semibold tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-7 py-3.5 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-300 hover:brightness-[1.08] active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[var(--editable-radius)] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-1.5 hover:shadow-[0_28px_60px_-24px_rgba(13,19,16,0.35)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use the dark inverted panels (nav/hero/footer/CTA) sparingly for premium rhythm against the light canvas.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
